ALTER TABLE clientes ALTER COLUMN logradouro DROP NOT NULL;
ALTER TABLE clientes ALTER COLUMN bairro DROP NOT NULL;
ALTER TABLE clientes ALTER COLUMN cidade DROP NOT NULL;
ALTER TABLE clientes ALTER COLUMN uf DROP NOT NULL;
ALTER TABLE clientes ALTER COLUMN cep DROP NOT NULL;

